development:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: devops_on_demand_production
test:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: devops_on_demand_production
production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: devops_on_demand_production
